### ISSUE TITLE
איך נכנסים לבתים?

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#1]
העיצוב ממש יפה, בדיוק כמו בציורים שלכם! 
הצלחתי ללכת ימינה ושמאלה, אבל לא הבנתי מה עוד אני אמור לעשות - למשל איך נכנסים לבתים?

**Comment by neyney10** [comment]
היי, מצטערים לגלות רק עכשיו שנפתחה פניה פה במערכת,
מאז אנחנו עושים עוד שיפורים ומרחיבים.

בנוגע לשאלתך, בגרסא המתאימה לתאריך שבו הגבת, ניתן לטייל בעיר ולהתרשם ממנה, 
כמו כן ניתן להיכנס לחדרים ומבנים באמצעות הכפתור במקלדת 
"H".

ובחדר של האפיה ניתן ללחו על המקש
"a"
כדי לשלב אוכל

כמו כן, ניתן לנסות ללכוד מומיות עם נייר טואלט באמצעות הכפתור במקלד
"B".
רק לשים לב שהפונקציונליות הזו נסיונית ואינה שלמה .

בגרסאות המאוחרות יותר מזו ניתן ללחוץ על המקש
"i"
כדי להציג הוראות.

**Comment by erelsgl** [comment]
הבנתי, מעולה. אשמח לקבל קישור לגירסה המעודכנת ביותר

**Comment by LioraPevzner** [comment]
נכון לכרגע הגרסא הכי מעודכנת שאעלנו זו הגרסא מלפני כשבוע , בה ניתן לשחק כאן (https://pikateam.itch.io/numosalphe)
ברגעים אלו אנו עובדים על הרכבת שלבי המשחק הלימודיים, מקווים לעדכן בקרוב עם קישור מעודכן יותר.

**Comment by LioraPevzner** [comment]
אעלנו גרסא חדשה יותר ל-itch נמצאת באותה הכתובת ששלחנו לך.

**Comment by erelsgl** [comment]
<div dir="rtl">
הבנתי, עכשיו הרבה יותר ברור.

אבל לא כדאי לשים את כל ההוראות במסך אחד - אנשים לא קוראים ולא זוכרים. אלא צריך לשים את ההוראות של כל שלב במקום שבו זה רלבנטי. למשל, כשאדם מתקרב לבניין - לכתוב לו בקטן "press H to enter", וכשאדם בתוך הבניין "press A".
</div>

**Comment by LioraPevzner** [comment]
בוצע בעדכון האחרון שעשינו, מקווים לעלות אותו ברגע שנסיים לסדר אותו מבחינת שאר הדברים.

**Comment by erelsgl** [comment]
אהבתי את מה שהוספתם עכשיו - שדמות מהמשחק אומרת לכם מה לעשות ואיך להיכנס
