### ISSUE TITLE
ממלכת נאמברין או ממלכת הטבעיים?

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#10]
<div dir=rtl>
בסיפור בהתחלה היא נקראת נאמברין, וזה לא דווקא טבעיים (נאמבר = מספר כלשהו).
ואז במשימה הראשונה אנחנו פתאום מגלים שהיא בעצם נקראת "ממלכת הטבעיים" - זה מבלבל.
אני מציע לקרוא לה מהתחלה "ממלכת המספרים הטבעיים".

**Comment by LioraPevzner** [comment]
הטקסט הוחלף ב: "הגעתם בהצלחה לנאמברין - ממלכת המספרים הטבעיים להציל את אחיכם.."
