### ISSUE TITLE
מה המשמעות של כתב החרטומים?

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#2]
<div dir="rtl">

נתקלתי במומיה, לחצתי על B ופגעתי בה בעזרת נייר טואלט, ואז הופיע לי דף עם כתב חרטומים שלא הבנתי - מה זה אומר?

</div>

**Comment by LioraPevzner** [comment]
מוזר שאנחנו לא מקבלים התראות על כך שאתה מפרסם אצלנו הודעה באיסוס.
מאז שידרגנו כמה פעמים את הגרסא וכרגע עלתה הגרסא המעודכנת ביותר וזו שמבחינתנו היא מספיקה לדמו לאוויר ושמה כבר הדברים יותר ברורים.
בקשר לשאלה, הכתב חרטומים הזה משמש כרקע עבור השאלה המתמטית שהוספנו בגרסא החדשה שלנו שאפשר למצוא אותה כאן
https://pikateam.itch.io/numosalphe

**Comment by erelsgl** [comment]
הבנתי, יפה מאד. עכשיו יש בעיה עם החידה - אני כותב פתרון ולוחץ על אנטר ולא קורה כלום.

**Comment by LioraPevzner** [comment]
הי,לוחצים על מקש היציאה, איקס למעלה מצד שמאל

**Comment by neyney10** [comment]
מסכים שזה לא אינטואטיבי,
יש באג ביוניטי שאי אפשר לסגור את החלון באותו רגע שמסיימים לכתוב, אז היינו צריכים באופן זמני להזיז את הבדיקה והסגירה של החידה לכפתור סגירה של החידה, בהמשך נחשוב על פתרון יצירתי יותר.

**Comment by erelsgl** [comment]
<div dir="rtl">
הבנתי. אם כך עדיף לשים את הכפתור הזה ליד תיבת-הטקסט, כך שהשחקן יבין שהוא אמור ללחוץ עליו אחרי שהוא סיים לכתוב.
ולשנות את צורת הכפתור מ X ל V.
</div>

**Comment by LioraPevzner** [comment]
שיניתי את כפתור היציאה לכפתור של "בדוק פיענוח".
כרגע אין כפתור יציאה בגלל שיש איזה בעיתיות עם ההגדרה שלו (ניסינו לפתור את הבעיה הזו אבל זה יותר מסובך ממה שחשבנו, ככה שהאופציה המצוינת מעל היא זו שהלכנו עליה נכון לכרגע).

**Comment by erelsgl** [comment]
נראה מעולה
