### ISSUE TITLE
מה משמעות המספרים בתוך הבניין?

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#3]
<div dir="rtl">
באחד הבניינים, לחצתי על A  והופיעו כל מיני מספרים.
בכל פעם שלחצתי על A המספרים התחלפו.
מה המשמעות שלהם?

</div>

**Comment by LioraPevzner** [comment]
הוספנו הערות הסבר בתחתית המסך שאמורות להסביר מה צריך לעשות וכיצד (מבחינת מקשים והכול).
בתקופה ההיא השלב לא עבד היום כן,  המטרה בשלב הזה היא לקחת ולהביא כל פעם לפרמה את המספר הנמוך ביותר העומד בתנאי עיקרון הסדר הטוב. פירושו, להביא כל פעם לפרמה את המספר הנמוך ביותר החיובי הגבוהה מ-0

**Comment by erelsgl** [comment]
<div dir="rtl">
שיחקתי עכשיו, ממש יפה. אהבתי במיוחד את ההערות של מר פפיון על המספר אפס ועל המספרים השליליים - זו בדיוק הדרך הנכונה להעביר את הרעיונות שאתם רוצים. השחקן מנסה, טועה, ומתוך הטעות הוא לומד.

הצעה: את ההערה על "עיקרון הסדר הטוב" אפשר להעביר להתחלה: כשאתם נכנסים, מר פפיון יגיד לכם משהו כמו "אצלנו בממלכת המספרים הטבעיים יש חוק-יסוד הנקרא "עקרון הסדר הטוב" - בכל קבוצה יש מספר קטן ביותר. אבל הגמלים שלי בלבלו לי את הסדר וכו' - ... האם תוכלו להביא לי את המספר הקטן ביותר?".

(והייתי מוריד את את ראשי-התיבות באנגלית  POW - זה רק מבלבל).
</div>

**Comment by LioraPevzner** [comment]
תודה רבה,
בנוגע לכתיבת העיקרון בתחילת המשחק, הגענו למסקנה שאם אנחנו נגיד לשחקנים מההתחלה את החוקיות השלמה של העיקרון ומה פירושו אז הם יפספסו את "שלב הניסוי" ,פירושו של דבר שהם פשוט יעבדו על אוטומט, ילכו על הערך שעומד בתנאים ויסגרו את הפינה. לעומת זאת אם אנו ניתן להם לנסות ולבדוק הם יוכלו באמצעות הפידבקים של הדמות לקבל קצת יותר ניסיון ויותר "תחושה של העיקרון" ככל שהם יתנסו וינסו יותר מספרים ויקבלו את התגובה המתאימה מלה פרמה.

**Comment by erelsgl** [comment]
<div dir="rtl">

הבנתי. מצד שני, כמו שזה עכשיו, לא ברור ל

**Comment by erelsgl** [comment]
הבנתי, יפה מאד
