### ISSUE TITLE
הבניין הימני זהה לראשון

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#4]
<div dir="rtl">
כשנכנסים לבניין הימני ביותר, מגיעים לאותו חדר מלא מספרים כמו כשנכנסים לבניין הראשון באמצע.

</div>

**Comment by LioraPevzner** [comment]
זה דבר שלא השתנה בגרסא המעודכנת ביותר, זאת משום שנכון לכרגע הבניין הימני ביותר והבניין השמאלי ביותר עדיין לא בנויים,
ברגע שיתאפשר לנו (לא בטוח שבשלב הדמו) אנחנו נעדכן אותם בהתאם. (פשוט עדיין אין ציורים מתאימים עבורם).

**Comment by erelsgl** [comment]
<div dir="rtl">
הבנתי. אם כך עדיף להוריד אותם כדי שלא יבלבלו את השחקן. אפשרות אחרת היא לשים שם דמות שאומרת "הבניין סגור לרגל שיפוצים" או משהו כזה :)
</div>

**Comment by LioraPevzner** [comment]
סודר, הוספתי את החנות של מר פלוס.
מה שכן הדמות אומרת לו שהחנות בשיפוצים ושיבוא בהמשך, ככה שרק החדר מוכן, אין עדיין ממש מה לקנות או לראות שמה (כלומר יש עוד אלמנטים להוסיף, אבל לבנתיים המקום קיים, פשוט צריך לשפץ אותו )

**Comment by erelsgl** [comment]
<div dir=rtl>
נראה מעולה. אבל יש בעיה אחרת - כשיוצאים מהדלת, חוזרים לנקודת ההתחלה במקום לנקודה שממנה נכנסנו בדלת.
אותה בעיה יש באוהל של הנחשית.

**Comment by LioraPevzner** [comment]
זו בעיה ידועה, מה שקורה הוא שכאשר חוזרים מכל אחד מהסצנות הללו חוזרים לסצנה המקורית שהיא הסצנה של מצרים שבה המיקום של השחקן הוא המיקום הראשוני, אנחנו מקווים להספיק להוסיף כלי שישמור את המיקום האחרון שבו עמד השחקן בסצנה של מצרים ואז להחזיר למיקום המדובר כל פעם בה הוא יוצא ממקום מסוים.

**Comment by erelsgl** [comment]
<dir dir=rtl>
תראו אם ההסבר כאן עוזר לכם: https://stackoverflow.com/q/42393259/827927

**Comment by LioraPevzner** [comment]
עובד:)
