### ISSUE TITLE
שלט "יציאה"

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#6]
<div dir="rtl">
במקום להגיד לשחקן במילים "כדי לצאת יש לנוע לצד הכי שמאלי", יותר פשוט לשים על הקיר שלט עם חץ שמאלה שכתוב עליו "יציאה".
</div>

**Comment by LioraPevzner** [comment]
רעיון טוב,  נאמץ אותו, תודה

**Comment by LioraPevzner** [comment]
בוצע, שונה במקומות הדרושים לשלט של יציאה במקום הכיתוב שהיה קודם לכן.

**Comment by erelsgl** [comment]
נראה מעולה. אבל משום-מה, כשאני בחנות של מר פפיון ולוחץ על 
A
השלט נעלם.

**Comment by LioraPevzner** [comment]
זה כי מדובר בסצנות שונות, סידרתי, תודה:)
