### ISSUE TITLE
גודל הפונט

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#8]
<div dir="rtl">
בתשובה לשאלתכם - לטעמי הפונט קטן מדי. תסתכלו על משחקי מחשב שאתם מכירים - הפונט בדרך-כלל יותר גדול.
מצד שני, אני לא יודע איך אפשר להגדיל את הפונט ועדיין להכניס את כל הטקסט למקום המתאים.
פתרון אפשרי: להשאיר את הפונט כמו שהוא, אבל אם השחקן לוחץ עם העכבר על הטקסט - הוא יראה את הטקסט בגדול.
</div>

**Comment by neyney10** [comment]
מה עם כמו במשחקי טקסט? שכל פעם מוצג לך רק חלק מהטקסט, והשחקן יכול לנווט קדימה או אחורה בטקסט כדי להמשיך לראות את שאר החלקים שאינם מוצגים לו ( כמו דפים)

**Comment by erelsgl** [comment]
<div dir="rtl">
זו אפשרות טובה. אנשים שמכירים משחקי טקסט רגילים לזה, אז יהיה להם קל להבין מה קורה.
צריך רק לוודא שהשחקן יכול לחזור להתחלה אם פספס משהו.
</div>

**Comment by erelsgl** [comment]
<div dir="rtl">
בכל מקרה, שינוי הפונט הוא בעדיפות נמוכה, כי גם כך עדיין אפשר לקרוא

**Comment by LioraPevzner** [comment]
אם אפשר אשמח לראות תמונה של המסך מצילום חיצוני של הסך (למשל לצלם עם הפלאפון) כדי לראות את גודל הפונט,
כי למשל אצלי על המחשב הפונט נראה די בולט ובגודל בינוני, על כן הייתי שמחה לדעת מה גודל המסך שברשותך אם אפשר ולראות כיצד זה נראה כדי להבין קצת יותר עד כמה להגדיל ככה שכאשר נגדיל בהמשך נדע לאן לכוון.

**Comment by LioraPevzner** [comment]
נכון לכרגע הבנו שגודל הפונט מושפע מאלמנטים של רזולוציית מסך, מאמינים שנסדר את זה בעתיד בגרסאות הבאות שנוציא למשחק.
