### ISSUE TITLE
לא הבנתי מה צריך לעשות בחידה עם הלבנים

### ISSUE THREAD

**Issue by erelsgl** [PikaTeam/NumosAlphaVersion#9]
<div dir=rtl>
אחרי שהרכבתי כמה צירופים, הגעתי לשלב שאומר "נסה למצוא עוד שילובים כי אני צריכה שתיים", ומשם לא הצלחתי להתקדם.
חשבתי להביא 7 ו-21, אבל לא היה 21.
וכשהבאתי נניח 7, היא אמרה לי "כל הכבוד, מצאת 0" - למה 0?

**Comment by LioraPevzner** [comment]
אוקי מה שהולך במשימת הלבנים זה שני שלבים.
בשלב הראשון מביאים לך מספר שמורכב מ: ראשוני א * ראשוני א * ראשוני ב
עליך להביא בסיבוב הראשון ראשוני א , ראשוני א וראשוני ב
בסיבוב השני עליך להביא תכפולה של ראשוני א * ראשוני א ולהביא לחוד את ראשוני ב
בשלב השלישי להביא לך את הערך שממנו מורכבת הפירמידה.

בשלב השני זה אותו רעיון רק שכאן אתה צריך להביא בהתחלה את שלוש הערכים כמוב שלב הראשון
ובסיבוב השני עליך להביא את הסכום של ראשוני א * ראשוני ב ולחוד את ראשוני א
לבסוף יש לך את אותו סעיף 3 כמו בשלב א

אני צריכה להוסיף לשלב הזה הערה של מה קורה אם השחקן מביא מספר שהוא לא מספר ראשוני, להגיד לו שהמספר שהוא הביא לא מתאים לסוגיה כי מספר שהוא לא ראשוני הוא מספר פריק ולכן ככה וככה. אבל יש בעיתיות מסוימת בזה כי ייתכן שזה יבלבל אותו בסיבוב השני שבו כן ייתכן מצב שהוא יביא מספר פריק. 

בנוגע להשגת אפס זה טעות טיפו, הוא אמור להגיד לך שהשגת X מתוך Y שאתה צריך להניח מאותו הסוג בפירמידה, ככה שהשחקן ידע שהוא שם דברים שצריך, אני מקווה לעבור על השלב הזה שוב בהמשך, כרגע אני לא כל כך בטוחה איך לחדד בו דברים כי יש בעיתיות מסוימת, כלומר כן אפשר בסיבוב הראשון לבדוק את עניין הראשוני או לא, שמה זה אמור להיות ברור אבל בסיבוב השני צריך לחשוב איך מכוונים אותו למציאת הערכים הדרושים.

**Comment by LioraPevzner** [comment]
אוקי, סידרתי חלק מהבעיות שהיו בשלב, הוספתי כמה הערות ואני אראה בהמשך האם יש דרך לחדד אותו יותר.

**Comment by erelsgl** [comment]
<div dir=rtl>
זה אכן שלב מאתגר, אשמח לחשוב על זה ביחד בשעת הקבלה.

**Comment by LioraPevzner** [comment]
סגור,
באיזה שעה מהזמן המוקצב לשעות הקבלה מתאים לך שנגיע?

**Comment by erelsgl** [comment]
מתי שנוח לכם
